# Generated by Django 3.0.5 on 2020-04-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=100000),
        ),
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='title of the product', max_length=255),
        ),
    ]
